"""Tests for the managed-block helpers in cli_shared.

Two regressions drove v0.6.1:
1. .gitignore was getting HTML-style markers (`<!-- coord:begin -->`),
   which aren't valid comment syntax in gitignore files. Git treats
   them as never-matching path patterns -- silently noisy. Real fix:
   write `# coord:begin` markers in .gitignore (and accept either
   style for back-compat detection).
2. Markers don't self-document. An agent that read CLAUDE.md saw the
   block as fair game and hand-edited it. Embedding an explicit
   AUTO-GENERATED warning inside the block makes future agents pause.
"""

from __future__ import annotations

from pathlib import Path

from coordination.cli_shared import (
    MANAGED_BEGIN,
    MANAGED_END,
    MANAGED_HASH_BEGIN,
    MANAGED_HASH_END,
    ensure_gitignore_entry,
    ensure_managed_block,
)


def test_gitignore_uses_hash_style_markers_on_fresh_write(tmp_path: Path) -> None:
    """A repo with no existing .gitignore should get hash-style comment
    markers (valid gitignore syntax), not HTML-comment markers."""
    ensure_gitignore_entry(tmp_path, ".coordination/local.env")
    text = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert MANAGED_HASH_BEGIN in text
    assert MANAGED_HASH_END in text
    # The HTML markers must NOT appear in .gitignore -- agents see them
    # as broken syntax and "fix" them, drifting the repo off the
    # detection contract.
    assert MANAGED_BEGIN not in text


def test_gitignore_block_carries_autogenerated_warning(tmp_path: Path) -> None:
    """The first content line of the managed gitignore block is an
    AUTO-GENERATED warning, so a hand-editor sees the warning before
    the entries themselves."""
    ensure_gitignore_entry(tmp_path, ".coordination/local.env")
    text = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert "AUTO-GENERATED" in text
    assert "do not hand-edit" in text.lower()


def test_gitignore_migrates_html_markers_to_hash_markers(tmp_path: Path) -> None:
    """A repo that was set up by an older coord version has HTML markers
    in its .gitignore. The next call to ensure_gitignore_entry must
    detect the existing block and rewrite it with hash markers,
    without losing the entry or duplicating it."""
    legacy = (
        "node_modules/\n"
        "\n"
        f"{MANAGED_BEGIN}\n"
        ".coordination/local.env\n"
        f"{MANAGED_END}\n"
    )
    (tmp_path / ".gitignore").write_text(legacy, encoding="utf-8")

    ensure_gitignore_entry(tmp_path, ".coordination/local.env")

    text = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    # Hash markers replaced the legacy HTML markers.
    assert MANAGED_HASH_BEGIN in text
    assert MANAGED_HASH_END in text
    assert MANAGED_BEGIN not in text
    assert MANAGED_END not in text
    # Entry is preserved exactly once.
    assert text.count(".coordination/local.env") == 1
    # Pre-existing content (node_modules) was not damaged.
    assert "node_modules/" in text


def test_managed_block_keeps_html_markers_in_markdown(tmp_path: Path) -> None:
    """Markdown files (CLAUDE.md / AGENTS.md / cursor) keep the
    HTML-style markers because those render as invisible comments in
    rendered Markdown -- exactly what a managed block wants."""
    target = tmp_path / "CLAUDE.md"
    ensure_managed_block(target, "## Section\n\nbody text")
    text = target.read_text(encoding="utf-8")
    assert MANAGED_BEGIN in text
    assert MANAGED_END in text


def test_managed_block_carries_autogenerated_warning(tmp_path: Path) -> None:
    target = tmp_path / "CLAUDE.md"
    ensure_managed_block(target, "## Section\n\nbody text")
    text = target.read_text(encoding="utf-8")
    assert "AUTO-GENERATED" in text
    assert "do not hand-edit" in text.lower()


def test_managed_block_recovers_from_hash_marker_vandalism(
    tmp_path: Path,
) -> None:
    """If an agent hand-edited a Markdown file's managed block and
    swapped the HTML markers for hash-style markers, the next coord
    upgrade must still recognise the block and replace it with proper
    HTML markers, not append a duplicate. This is the exact astrowars
    incident: agent-rewritten markers caused detection to think no
    block existed."""
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "# AGENTS\n\n"
        f"{MANAGED_HASH_BEGIN}\n"
        "old hand-edited content\n"
        f"{MANAGED_HASH_END}\n"
        "\nproject notes below\n",
        encoding="utf-8",
    )

    ensure_managed_block(target, "## new content")

    text = target.read_text(encoding="utf-8")
    # Block is replaced (single instance), HTML markers restored.
    assert text.count("coord:begin") == 1, text
    assert text.count("coord:end") == 1, text
    assert MANAGED_BEGIN in text
    assert "## new content" in text
    assert "old hand-edited content" not in text
    # Surrounding content preserved.
    assert "project notes below" in text
