"""Guard against the drift that shipped in v0.28.1: ``__version__`` lived
in ``coordination/__init__.py`` as a hand-maintained constant while
``pyproject.toml`` held the canonical version. The two could disagree
silently, producing a container image whose ``/readyz`` reports an older
version than the tag it was built from.

The fix in v0.28.2 makes ``coordination.__version__`` read from
``importlib.metadata.version("coord-mcp-server")`` so there is only one
source of truth at runtime. This test pins that contract from both
sides:

1. ``coordination.__version__`` must equal the metadata version of the
   installed ``coord-mcp-server`` distribution.
2. The metadata version must equal ``pyproject.toml``'s
   ``[project].version`` field, which is what hatchling writes into
   the dist-info on build.

Together these assertions catch every plausible drift pattern: a
forgotten constant bump, a stale dist-info, or a build that wrote the
wrong METADATA.
"""

from __future__ import annotations

import tomllib
from importlib.metadata import version as _pkg_version
from pathlib import Path

import coordination


PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def _pyproject_version() -> str:
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    return str(data["project"]["version"])


def test_runtime_version_matches_distribution_metadata() -> None:
    """``coordination.__version__`` is sourced from importlib.metadata,
    so it must equal what the installed dist-info reports."""
    assert coordination.__version__ == _pkg_version("coord-mcp-server"), (
        f"coordination.__version__ ({coordination.__version__!r}) does not "
        f"match importlib.metadata.version('coord-mcp-server') "
        f"({_pkg_version('coord-mcp-server')!r}). The package was probably "
        f"rebuilt without reinstalling; run `pip install -e .` and rerun."
    )


def test_distribution_metadata_matches_pyproject() -> None:
    """The dist-info METADATA file is generated by hatchling from
    pyproject.toml at build time. They must match, otherwise the build
    pipeline shipped a stale wheel and the version-tag verification in
    ``.github/workflows/release.yml`` (publish-pypi job) would let the
    discrepancy through silently."""
    assert _pkg_version("coord-mcp-server") == _pyproject_version(), (
        f"installed coord-mcp-server metadata "
        f"({_pkg_version('coord-mcp-server')!r}) does not match "
        f"pyproject.toml [project].version ({_pyproject_version()!r}). "
        f"The dev environment is stale; run `pip install -e .` to refresh."
    )


def test_pyproject_version_is_pep440_clean() -> None:
    """The image-tag pinning job in release.yml builds the tag string
    `v{pyproject_version}` and digests it. Anything that would break
    `packaging.version.Version` here would also break the publish-pypi
    job's version verification step, so catch it locally first."""
    from packaging.version import Version

    Version(_pyproject_version())
    Version(coordination.__version__)
