"""Regex-based Ruby symbol extractor (fallback backend).

This backend is used when the ``tree-sitter-ruby`` wheel is not installed or
when the operator forces it via ``COORD_SYMBOL_PARSER=regex``. It exists so the
coord MCP wrapper can still ship symbol claims on machines without the native
tree-sitter wheels.

Top-level pass
--------------

Conventional Ruby indents class / module / method bodies, so the regex anchors
every top-level match to column zero. That single rule does the heavy lifting
of excluding members: any ``def`` or nested ``class`` / ``module`` inside a
body must be indented, so it cannot match the column-zero anchor.

Recognised at column zero:

- ``class Name`` -- ``kind='class'``. The captured name may carry a namespace
  (``class Foo::Bar``); the optional superclass clause (``< Base``) is not part
  of the captured name.
- ``module Name`` -- ``kind='class'`` (the Symbol kind set has no separate
  ``module`` kind).
- ``def name`` and ``def self.name`` / ``def Recv.name`` -- ``kind='function'``.
  The receiver of a singleton method is consumed but not captured, so
  ``def self.create`` emits ``Symbol(name='create', ...)``.

Member pass
-----------

After the top-level pass the backend runs an indentation-aware secondary pass
over each top-level ``class`` / ``module`` slice (from the namespace header to
the next column-zero declaration, or end of file). The body indent is inferred
as the smallest non-zero leading-whitespace length on a non-blank, non-comment
line. Indented ``def`` (including ``def self.x``) whose indent matches the
inferred body indent are emitted as method symbols with ``parent`` set to the
enclosing namespace. A nesting stack tracks inner ``class`` / ``module`` so a
method on ``Outer::Inner`` surfaces with ``parent='Outer::Inner'``. Lines
indented deeper than the current body indent are treated as nested (defs inside
a method body, members of a deeper namespace) and follow the stack.

Known false-negatives (documented so callers know the trade-off):

- Method names built from operators (``def <=>``, ``def []``, ``def +``) are
  not captured: the name regex only matches identifier-shaped names with an
  optional ``?`` / ``!`` / ``=`` suffix.
- Methods generated by metaprogramming (``attr_accessor :x``,
  ``define_method(:y)``) are invisible -- there is no ``def`` keyword to match.
- ``=begin`` / ``=end`` block comments and heredoc / string bodies that place
  ``class``, ``module``, or ``def`` at column zero are mis-matched as
  declarations. A context-tracking parser would be needed to defend against
  this; the tree-sitter backend handles it correctly.
- One-line bodies (``class X; def y; end; end`` on a single line) yield the
  namespace but no members, because there is no indented body to scan.
- ``class << self`` singleton-class blocks are not recognised as a namespace;
  methods defined inside them are treated as members of the surrounding class
  by indentation, which over-attributes them. Real coordination on such
  methods is rare.
- Body-indent detection is character-count based, so bodies that mix tabs and
  spaces within the same namespace can be miscounted: a tab counts as one
  character, not a logical column step. Conventionally indented bodies (all
  two-space, all four-space, or all single-tab) work correctly.

``end_line`` is approximated as ``start_line`` throughout because the regex
cannot track ``end`` matching without becoming a full parser. The tree-sitter
backend is the primary correctness path; this fallback is intentionally
imprecise.
"""

from __future__ import annotations

import re

from . import Symbol

# A Ruby method name: identifier with an optional predicate / bang / setter
# suffix (``valid?``, ``save!``, ``name=``).
_METHOD_NAME = r"[A-Za-z_][A-Za-z0-9_]*[?!=]?"

# A namespace name: a constant, optionally scope-qualified (``Foo::Bar``).
_CONST_NAME = r"[A-Z][A-Za-z0-9_]*(?:::[A-Z][A-Za-z0-9_]*)*"

# ``class Name`` at column zero. A superclass clause (``< Base``) and a
# scope-resolution name (``class Foo::Bar``) are both tolerated; only the
# constant path is captured.
_CLASS_RE = re.compile(
    r"^class\s+(?P<name>" + _CONST_NAME + r")",
    re.MULTILINE,
)

# ``module Name`` at column zero.
_MODULE_RE = re.compile(
    r"^module\s+(?P<name>" + _CONST_NAME + r")",
    re.MULTILINE,
)

# ``def name`` / ``def self.name`` / ``def Recv.name`` at column zero. The
# optional receiver (``self`` or a constant) before the dot is consumed but
# not captured.
_DEF_RE = re.compile(
    r"^def\s+(?:(?:self|" + _CONST_NAME + r")\.)?(?P<name>" + _METHOD_NAME + r")",
    re.MULTILINE,
)

# Indented ``def`` / ``def self.x`` for the namespace-body pass.
_INDENTED_DEF_RE = re.compile(
    r"^(?P<indent>[ \t]+)def\s+"
    r"(?:(?:self|" + _CONST_NAME + r")\.)?(?P<name>" + _METHOD_NAME + r")",
)

# Indented ``class`` / ``module`` for the namespace-body pass.
_INDENTED_NAMESPACE_RE = re.compile(
    r"^(?P<indent>[ \t]+)(?P<keyword>class|module)\s+(?P<name>" + _CONST_NAME + r")",
)


def _line_of(content: str, offset: int) -> int:
    """1-indexed line number containing the byte at ``offset``."""

    return content.count("\n", 0, offset) + 1


def _infer_body_indent(slice_text: str) -> int:
    """Return the smallest non-zero indent (in characters) inside ``slice_text``.

    Blank lines and comment-only lines do not contribute. Returns ``0`` when
    the slice has no indented content (e.g. a single-line namespace body).
    """

    smallest = 0
    for raw_line in slice_text.split("\n"):
        stripped = raw_line.lstrip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        indent_len = len(raw_line) - len(stripped)
        if indent_len == 0:
            continue
        if smallest == 0 or indent_len < smallest:
            smallest = indent_len
    return smallest


def _member_matches_in_slice(
    content: str,
    slice_start: int,
    slice_end: int,
    namespace_name: str,
) -> list[Symbol]:
    """Scan ``content[slice_start:slice_end]`` for namespace-body members.

    Walks an indentation stack so nested ``class`` / ``module`` definitions
    (and their members) surface with the full ``Outer::Inner::method``
    ancestor path. The slice runs from the namespace header offset to the next
    column-zero declaration (or end of file). Lines whose indent equals the
    current top-of-stack namespace's body indent emit as members of that
    namespace; deeper-indented lines (defs inside a method body) stay excluded.

    Tracks namespaces as a stack of ``(header_indent, full_path)``. The outer
    namespace header sat at column zero, so its body indent is the inferred
    ``body_indent_step``. A line whose indent equals ``top.header_indent +
    body_indent_step`` counts as a direct member of that namespace.
    """

    slice_text = content[slice_start:slice_end]
    body_indent_step = _infer_body_indent(slice_text)
    if body_indent_step == 0:
        return []

    out: list[Symbol] = []
    # Stack of (namespace_header_indent, full_path). The outer namespace
    # header was at column zero so its body lives at body_indent_step.
    stack: list[tuple[int, str]] = [(0, namespace_name)]

    def member_path_for(line_indent: int) -> str | None:
        """Return the namespace path whose body matches ``line_indent``.

        Pops any stack entries that have gone out of scope (their body indent
        exceeds ``line_indent``), then returns the top entry's path iff its
        body indent equals ``line_indent``.
        """

        while stack and stack[-1][0] + body_indent_step > line_indent:
            stack.pop()
        if stack and stack[-1][0] + body_indent_step == line_indent:
            return stack[-1][1]
        return None

    line_offset = 0
    for raw_line in slice_text.split("\n"):
        if raw_line.strip() == "" or raw_line.lstrip().startswith("#"):
            line_offset += len(raw_line) + 1
            continue
        indent_len = len(raw_line) - len(raw_line.lstrip())
        if indent_len == 0:
            line_offset += len(raw_line) + 1
            continue
        path = member_path_for(indent_len)
        if path is None:
            line_offset += len(raw_line) + 1
            continue
        absolute_offset = slice_start + line_offset
        line = content.count("\n", 0, absolute_offset) + 1

        namespace_match = _INDENTED_NAMESPACE_RE.match(raw_line)
        if namespace_match:
            inner_name = namespace_match.group("name")
            full = f"{path}::{inner_name}"
            out.append(
                Symbol(
                    name=inner_name,
                    kind="class",
                    start_line=line,
                    end_line=line,
                    parent=path,
                )
            )
            stack.append((indent_len, full))
            line_offset += len(raw_line) + 1
            continue

        def_match = _INDENTED_DEF_RE.match(raw_line)
        if def_match:
            out.append(
                Symbol(
                    name=def_match.group("name"),
                    kind="function",
                    start_line=line,
                    end_line=line,
                    parent=path,
                )
            )
        line_offset += len(raw_line) + 1

    return out


def extract(content: str) -> list[Symbol]:
    """Return top-level declarations and namespace members found by regex.

    Top-level matches are anchored to column zero so any indented definition
    is excluded from the top-level pass. For each top-level ``class`` /
    ``module`` the backend runs an indentation-aware secondary pass to surface
    members with ``parent`` pointing at the enclosing namespace. ``end_line``
    equals ``start_line`` throughout because the regex cannot track ``end``
    scope without becoming a real parser.

    Order in the returned list follows ``start_line`` so callers that rely on
    file order get a deterministic sequence even though several independent
    regexes contribute. A namespace header always has a lower ``start_line``
    than its members, so the "namespace then its members" walk order matches
    the tree-sitter backend.
    """

    out: list[Symbol] = []

    # Top-level (column-zero) anchors. Collect every anchor offset so we can
    # compute namespace-body slices: a slice ends at the next column-zero
    # anchor (or end of file).
    top_level_starts: list[int] = []
    namespace_anchors: list[tuple[int, str]] = []

    for match in _CLASS_RE.finditer(content):
        name = match.group("name")
        out.append(
            Symbol(
                name=name,
                kind="class",
                start_line=_line_of(content, match.start()),
                end_line=_line_of(content, match.start()),
            )
        )
        top_level_starts.append(match.start())
        namespace_anchors.append((match.start(), name))

    for match in _MODULE_RE.finditer(content):
        name = match.group("name")
        out.append(
            Symbol(
                name=name,
                kind="class",
                start_line=_line_of(content, match.start()),
                end_line=_line_of(content, match.start()),
            )
        )
        top_level_starts.append(match.start())
        namespace_anchors.append((match.start(), name))

    for match in _DEF_RE.finditer(content):
        name = match.group("name")
        out.append(
            Symbol(
                name=name,
                kind="function",
                start_line=_line_of(content, match.start()),
                end_line=_line_of(content, match.start()),
            )
        )
        top_level_starts.append(match.start())

    # Member pass: for each top-level namespace, slice from its header to the
    # next column-zero anchor (or EOF) and scan for indented defs / namespaces.
    top_level_starts.sort()
    for ns_start, ns_name in namespace_anchors:
        slice_end = len(content)
        for start in top_level_starts:
            if start > ns_start and start < slice_end:
                slice_end = start
        out.extend(_member_matches_in_slice(content, ns_start, slice_end, ns_name))

    # Stable order: by start_line. The independent passes above would
    # otherwise interleave unpredictably; sorting keeps the output
    # deterministic and matches the tree-sitter "namespace then members" walk.
    out.sort(key=lambda s: s.start_line)
    return out
