"""Regex-based Rust symbol extractor (fallback backend).

Used when the ``tree-sitter-rust`` wheel is not installed or when the operator
forces it via ``COORD_SYMBOL_PARSER=regex``. It exists so coord-mcp can still
ship symbol claims on machines without the native tree-sitter wheels.

Top-level declarations are matched anchored to column zero (``re.MULTILINE`` +
``^``): ``fn``, ``struct``, ``union``, ``enum``, ``type`` aliases, ``trait``,
``const`` and ``static``. Visibility (``pub``, ``pub(crate)``) and a leading
``unsafe`` / ``async`` modifier on functions are tolerated.

Methods inside ``impl`` blocks are indented, so a pure column-zero anchor would
miss them. Unlike Go -- where methods are themselves top-level declarations with
the receiver in the signature -- Rust attaches methods to the type through an
``impl`` block whose body is indented. To make ``Type::method`` claims work in
the fallback, this backend runs one linear brace-depth scan that tracks the
enclosing ``impl <Type>`` header and attributes any ``fn`` found at impl-body
depth to that type as ``parent``. The scan counts ``{`` / ``}`` only; it is not
a full parser and does not understand strings, char literals, or comments that
contain braces.

Known false-negatives (documented so callers know the trade-off):

- Parenthesised / multi-line headers where the keyword and the name sit on
  separate lines (``impl<T>\n    Foo<T> {`` or a ``fn`` whose name wraps to the
  next line). Real rustfmt output keeps the keyword and name together, so this
  only bites hand-mangled or macro-printed source.

- A single-line impl body (``impl Foo { fn bar() {} }`` all on one line)
  yields no methods, because ``_IMPL_METHOD_RE`` requires the ``fn`` to start
  its own indented line; conventional multi-line rustfmt output works.

- Braces inside string literals, char literals, or ``//`` / ``/* */`` comments
  shift the brace-depth counter, which can mis-scope or drop an ``impl`` method.
  The tree-sitter backend handles these correctly; install the ``symbols``
  extra to get full coverage.

- Items generated by macros (``macro_rules!`` bodies, derive expansions) are
  invisible to a textual scan and never surface.

- Items declared inside a ``mod { ... }`` block or a function body are filtered
  by column-zero anchoring (they are indented). ``mod`` itself is a namespace,
  not a claimable unit, so it is never emitted.

- Raw identifiers (``fn r#match()``) capture the bare word after ``r#`` only
  when it matches ``\\w+``; the ``r#`` prefix is consumed but not part of the
  name.

``end_line`` is approximated as ``start_line`` because the regex cannot track
brace matching for the declaration body without becoming a full parser. Conflict
detection only uses the ``(file_path, name)`` pair, so this approximation does
not affect the coordination contract.
"""

from __future__ import annotations

import re

from . import Symbol

# Optional leading visibility + modifiers shared by the top-level patterns.
# ``pub``, ``pub(crate)``, ``pub(in path)`` etc. plus ``unsafe`` / ``async`` /
# ``const`` / ``extern`` modifiers that can precede ``fn``.
_VIS = r"(?:pub(?:\s*\([^)]*\))?\s+)?"
_FN_MODS = r"(?:(?:const|async|unsafe|extern(?:\s+\"[^\"]*\")?)\s+)*"

# fn Name [generic params] (
# Allows visibility and fn modifiers. ``r#`` raw-identifier prefix is consumed.
_FUNC_RE = re.compile(
    r"^" + _VIS + _FN_MODS + r"fn\s+(?:r#)?(?P<name>\w+)\s*[\(<]",
    re.MULTILINE,
)

# struct / union Name
_STRUCT_RE = re.compile(
    r"^" + _VIS + r"(?:struct|union)\s+(?P<name>\w+)",
    re.MULTILINE,
)

# enum Name
_ENUM_RE = re.compile(
    r"^" + _VIS + r"enum\s+(?P<name>\w+)",
    re.MULTILINE,
)

# trait Name
_TRAIT_RE = re.compile(
    r"^" + _VIS + r"(?:unsafe\s+)?trait\s+(?P<name>\w+)",
    re.MULTILINE,
)

# type Name = ...  (alias)
_TYPE_ALIAS_RE = re.compile(
    r"^" + _VIS + r"type\s+(?P<name>\w+)",
    re.MULTILINE,
)

# const | static [mut] Name :
_CONST_STATIC_RE = re.compile(
    r"^" + _VIS + r"(?:const|static)\s+(?:mut\s+)?(?P<name>\w+)\s*:",
    re.MULTILINE,
)

# impl [<generics>] [Trait for] Type {  -- header on a single line.
# The last ``\w+`` before the trailing ``{`` (after stripping generic args and
# an optional ``Trait for`` clause) is the implementing type name.
_IMPL_HEADER_RE = re.compile(
    r"^impl\b[^\n{]*?"
    r"(?:\bfor\s+)?"
    r"(?P<type>\w+)"
    r"(?:<[^\n{]*>)?\s*\{",
)

# An indented ``fn`` inside an impl body. Leading whitespace is required so this
# does not double-fire on top-level functions already captured by ``_FUNC_RE``.
_IMPL_METHOD_RE = re.compile(
    r"^\s+" + _VIS + _FN_MODS + r"fn\s+(?:r#)?(?P<name>\w+)\s*[\(<]",
)


def _line_of(content: str, offset: int) -> int:
    """1-indexed line number containing the byte at ``offset``."""

    return content.count("\n", 0, offset) + 1


def _impl_methods(content: str) -> list[tuple[int, str, str]]:
    """Find ``impl`` methods and their implementing type via a brace scan.

    Returns ``(offset, name, parent)`` tuples. The scan walks line by line,
    tracks brace depth, remembers the type name of the ``impl`` header that
    opened the current block, and attributes every ``fn`` found at that block's
    body depth to it. Only ``{`` / ``}`` counts drive the depth; the scan does
    not understand braces inside strings or comments (a documented limitation).
    """

    out: list[tuple[int, str, str]] = []
    # Stack of (depth_at_which_impl_opened, parent_type) for active impl blocks.
    impl_stack: list[tuple[int, str]] = []
    depth = 0
    offset = 0

    for line in content.splitlines(keepends=True):
        stripped = line.lstrip()
        header = _IMPL_HEADER_RE.match(stripped)

        # A ``fn`` at impl-body depth (directly inside the nearest open impl).
        if impl_stack:
            method = _IMPL_METHOD_RE.match(line)
            if method is not None and depth == impl_stack[-1][0] + 1:
                parent = impl_stack[-1][1]
                name_off = offset + method.start("name")
                out.append((name_off, method.group("name"), parent))

        opens = line.count("{")
        closes = line.count("}")

        if header is not None:
            # The impl block opens on this line; record the depth it sits at so
            # methods one level deeper attribute to this type.
            impl_stack.append((depth, header.group("type")))

        depth += opens - closes
        if depth < 0:
            depth = 0
        # Pop any impl blocks whose closing brace we have now passed.
        while impl_stack and depth <= impl_stack[-1][0]:
            impl_stack.pop()

        offset += len(line)

    return out


def extract(content: str) -> list[Symbol]:
    """Return top-level declarations found by the regex scan.

    Top-level matches are anchored to column zero (``re.MULTILINE`` + ``^``) so
    declarations under conventional indentation are excluded. Methods inside
    ``impl`` blocks are recovered by a separate brace-depth scan and carry the
    implementing type as ``parent``. Each match emits exactly one Symbol;
    ``end_line`` equals ``start_line``.

    Order in the returned list follows the byte offset of the match so callers
    that rely on file order get a deterministic sequence even though we run
    several independent regexes.
    """

    found: list[tuple[int, Symbol]] = []
    seen: set[tuple[str, str, int, str | None]] = set()

    def _record(
        name: str, kind: str, offset: int, parent: str | None = None
    ) -> None:
        line = _line_of(content, offset)
        key = (name, kind, line, parent)
        if key in seen:
            return
        seen.add(key)
        found.append(
            (
                offset,
                Symbol(
                    name=name,
                    kind=kind,
                    start_line=line,
                    end_line=line,
                    parent=parent,
                ),
            )
        )

    for match in _FUNC_RE.finditer(content):
        _record(match.group("name"), "function", match.start("name"))

    for match in _STRUCT_RE.finditer(content):
        _record(match.group("name"), "type", match.start("name"))

    for match in _ENUM_RE.finditer(content):
        _record(match.group("name"), "enum", match.start("name"))

    for match in _TRAIT_RE.finditer(content):
        _record(match.group("name"), "interface", match.start("name"))

    for match in _TYPE_ALIAS_RE.finditer(content):
        _record(match.group("name"), "type", match.start("name"))

    for match in _CONST_STATIC_RE.finditer(content):
        _record(match.group("name"), "const", match.start("name"))

    for offset, name, parent in _impl_methods(content):
        _record(name, "function", offset, parent=parent)

    found.sort(key=lambda pair: pair[0])
    return [sym for _, sym in found]
