apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coord-auth-vault
  namespace: coord
  labels:
    app.kubernetes.io/name: coord
    app.kubernetes.io/part-of: coord
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  path: apps/YOUR_CLUSTER/coord
  type: kv-v2
  refreshAfter: 1h
  destination:
    create: true
    name: coord-auth
    labels:
      app.kubernetes.io/name: coord
      source: vault
    transformation:
      templates:
        COORD_AUTH_TOKEN:
          text: "{{ .Secrets.auth_token }}"
