from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import httpx

from coordination.assets import AGENTS_SNIPPET, CLAUDE_SNIPPET, CURSOR_RULE, PRE_PUSH_SCRIPT
from coordination.cli_shared import (
    ensure_gitignore_entries,
    ensure_managed_block,
    ensure_prettierignore_entries,
    ensure_token_file,
    find_repo_root,
    state_paths,
    write_executable,
)
from coordination.envfile import read_env_file, update_env_file
from coordination.repo_config import RepoConfig


def _prompt_choice(prompt: str, choices: list[str], default: str) -> str:
    options = "/".join(choices)
    raw = input(f"{prompt} [{options}] ({default}): ").strip().lower()
    return raw if raw in choices else default


def _determine_tool(args) -> str:
    if args.tool:
        return args.tool
    if args.yes:
        return "claude"
    return _prompt_choice("Primary coding tool", ["claude", "codex", "cursor"], "claude")


def _determine_mode(args) -> str:
    if args.mode:
        return args.mode
    if args.yes:
        return "local"
    return _prompt_choice("Connection mode", ["local", "remote"], "local")


def _service_url(mode: str, explicit: str | None) -> str:
    if explicit:
        return explicit.rstrip("/")
    if mode == "local":
        return "http://127.0.0.1:8080"
    return "https://coord.example.com"


def _starter_owners(repo_root: Path) -> str:
    lines = [
        "# Starter ownership map generated by coord init",
        "# Tighten these boundaries as your team learns where conflicts happen.",
        "",
        "areas:",
    ]
    dirs = sorted(
        p.name
        for p in repo_root.iterdir()
        if p.is_dir() and not p.name.startswith(".") and p.name not in {"node_modules", "dist", "build"}
    )
    if not dirs:
        dirs = ["src"]
    for name in dirs[:8]:
        lines.extend(
            [
                f"  {name}:",
                "    paths:",
                f'      - "{name}/**"',
                "    owners: [team]",
                "",
            ]
        )
    lines.extend(
        [
            "  shared-root:",
            "    paths:",
            '      - "package.json"',
            '      - "README.md"',
            "    severity: hard",
            "    owners: [all]",
            "",
        ]
    )
    return "\n".join(lines)


def _detect_repo_id(repo_root: Path) -> str:
    """Best-effort repo identifier for a coord-managed repo.

    Order of preference:
    1. ``owner/repo`` slug parsed from ``git remote get-url origin``.
       Handles both HTTPS (``https://github.com/owner/repo.git``) and
       SSH (``git@github.com:owner/repo.git``) forms.
    2. The directory basename, when no origin remote is configured or
       the directory is not a git work tree.

    Never raises: a reliable repo id is more useful than a precise one,
    and the user can always override the value with an explicit
    ``repo_id`` in ``.coordination/config.toml``.
    """
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_root,
            check=False,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError):
        return repo_root.name

    if result.returncode != 0:
        return repo_root.name

    url = result.stdout.strip()
    # SSH form: git@host:owner/repo(.git)
    m = re.match(r"^[^@]+@[^:]+:([^/]+/[^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1)
    # HTTPS / git protocol form: scheme://host/path/owner/repo(.git)
    m = re.match(r"^[a-zA-Z]+://[^/]+/(?:[^/]+/)*([^/]+/[^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1)
    return repo_root.name


def _git_line(repo_root: Path, *args: str) -> tuple[int, str]:
    """Run a git command, returning (returncode, stripped stdout).
    Returns (-1, "") if git is unavailable. Never raises."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=repo_root,
            check=False,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError):
        return (-1, "")
    return (result.returncode, result.stdout.strip())


def _current_branch(repo_root: Path) -> str | None:
    rc, out = _git_line(repo_root, "rev-parse", "--abbrev-ref", "HEAD")
    return out if rc == 0 and out and out != "HEAD" else None


def _default_branch(repo_root: Path) -> str | None:
    """Best-effort default/integration branch: the ``origin/HEAD`` target,
    falling back to a local ``main`` or ``master``. None when it cannot
    be determined (so the caller stays quiet rather than guessing)."""
    rc, out = _git_line(
        repo_root, "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"
    )
    if rc == 0 and out:
        return out.rsplit("/", 1)[-1]
    for candidate in ("main", "master"):
        rc, _ = _git_line(
            repo_root, "rev-parse", "--verify", "--quiet", f"refs/heads/{candidate}"
        )
        if rc == 0:
            return candidate
    return None


def _has_staged_changes(repo_root: Path) -> bool:
    # `git diff --cached --quiet` exits 1 when the index has staged changes.
    rc, _ = _git_line(repo_root, "diff", "--cached", "--quiet")
    return rc == 1


def _is_gitignored(repo_root: Path, rel_path: str) -> bool:
    # `git check-ignore -q` exits 0 when the path is ignored.
    rc, _ = _git_line(repo_root, "check-ignore", "-q", rel_path)
    return rc == 0


# coord-generated MACHINE config (placeholder-bearing, regenerated by
# init/upgrade). Unlike the protocol docs (CLAUDE.md / AGENTS.md blocks,
# cursor rules) these carry no human content worth versioning and, when
# tracked, leak into contributor PRs. coord gitignores them and untracks
# any that an older coord version committed -- per-repo config now lives
# only in the gitignored .coordination/local.env (and, recommended, a
# user-scoped coord MCP server: `claude mcp add --scope user coord
# coord-mcp`).
_MACHINE_CONFIGS = (".mcp.json", ".cursor/mcp.json", ".codex/config.toml")


def _untrack_machine_configs(repo_root: Path) -> list[str]:
    """Stop git from tracking coord's generated machine configs that an
    older coord version committed. ``git rm --cached`` removes them from
    the index (so the next commit untracks them) while leaving the files
    on disk. Best-effort and idempotent: only acts on paths that are
    actually tracked. Returns the paths it untracked, for reporting."""
    untracked: list[str] = []
    for rel in _MACHINE_CONFIGS:
        rc, _ = _git_line(repo_root, "ls-files", "--error-unmatch", rel)
        if rc != 0:
            continue  # not tracked (or no git) -- nothing to do
        rc, _ = _git_line(repo_root, "rm", "--cached", "--quiet", rel)
        if rc == 0:
            untracked.append(rel)
    return untracked


def _warn_tracked_wiring_commit_risk(repo_root: Path, written: list[str]) -> None:
    """coord writes TRACKED files (.mcp.json, the CLAUDE.md / AGENTS.md
    managed block, .gitignore, etc.). On a contributor/feature branch a
    careless ``git add -A && commit`` sweeps them into that branch's pull
    request -- the failure mode behind several polluted PRs. Warn (never
    block: onboarding via a PR is legitimate) at the moment of risk,
    naming only the tracked files so the operator can stage coord's
    wiring by itself. ``.coordination/`` and ``.git/`` entries are local,
    and gitignored paths (e.g. the now-ignored .mcp.json) are excluded --
    git will not commit those, so they carry no PR-leak risk."""
    tracked = [
        path
        for entry in written
        if not (path := entry.split(" (")[0]).startswith((".coordination/", ".git/"))
        and not _is_gitignored(repo_root, path)
    ]
    if not tracked:
        return
    current = _current_branch(repo_root)
    default = _default_branch(repo_root)
    off_default = bool(current and default and current != default)
    staged = _has_staged_changes(repo_root)
    if not off_default and not staged:
        return
    print("", file=sys.stderr)
    print(
        "WARNING: coord wrote these TRACKED files (git will commit them):",
        file=sys.stderr,
    )
    for path in tracked:
        print(f"  {path}", file=sys.stderr)
    if off_default:
        print(
            f"You are on branch '{current}', not the default branch "
            f"'{default}'. Committing here puts coord's wiring into any "
            "pull request for this branch.",
            file=sys.stderr,
        )
    if staged:
        print(
            "The index already has staged changes; committing now would "
            "bundle coord's wiring with that unrelated work.",
            file=sys.stderr,
        )
    print(
        "Stage coord's wiring by itself (git add "
        + " ".join(tracked)
        + ") and commit it alone -- do not 'git add -A' it into other work.",
        file=sys.stderr,
    )
    print("", file=sys.stderr)


def _write_repo_config(
    repo_root: Path,
    tool: str,
    mode: str,
    service_url: str,
    repo_id: str | None = None,
) -> None:
    config = RepoConfig(
        version=1,
        tool=tool,
        mode=mode,
        service_url=service_url,
        ownership_file=".coordination/owners.yaml",
        repo_id=repo_id or _detect_repo_id(repo_root),
    )
    path = repo_root / ".coordination" / "config.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config.to_toml(), encoding="utf-8")


def _write_local_env(
    repo_root: Path,
    mode: str,
    service_url: str,
    repo_id: str | None = None,
    force: bool = False,
) -> bool:
    """Write or refresh ``.coordination/local.env``.

    Returns True when an existing non-placeholder ``COORD_AUTH_TOKEN`` was
    preserved. Re-running init is a supported, additive flow (e.g. a second
    ``--tool``), and the documented v0.42 workflow has operators paste
    repo-scoped tokens into this file -- so a re-init must not clobber a
    working token with the ``set-me`` placeholder (remote mode without
    COORD_AUTH_TOKEN exported) or the shared ``~/.coord/token`` (local
    mode). Only ``--force`` re-mints/backfills over an existing real token.
    Unmanaged keys and comments are preserved verbatim via the shared
    envfile updater.
    """
    path = repo_root / ".coordination" / "local.env"
    existing_token = read_env_file(path).get("COORD_AUTH_TOKEN", "")
    preserved = bool(
        existing_token
        and existing_token != PLACEHOLDER_AUTH_TOKEN
        and not force
    )
    if preserved:
        token = existing_token
    elif mode == "local":
        token = ensure_token_file(state_paths()["token_file"])
    else:
        token = os.environ.get("COORD_AUTH_TOKEN", PLACEHOLDER_AUTH_TOKEN)
    # COORD_API_URL powers coord-mcp and user shells; COORD_SERVICE_URL is
    # what the pre-push hook reads. Emit both so whichever tool sources
    # this file picks up the right endpoint -- this is what stops a remote
    # deployment from silently falling back to http://127.0.0.1:8080.
    updates = {
        "COORD_API_URL": service_url,
        "COORD_SERVICE_URL": service_url,
        "COORD_AUTH_TOKEN": token,
    }
    rid = repo_id or _detect_repo_id(repo_root)
    if rid:
        updates["COORD_REPO_ID"] = rid
    update_env_file(path, updates)
    return preserved


# Placeholder values written into every tracked MCP template
# (.mcp.json, .codex/config.toml, .cursor/mcp.json). The MCP wrapper
# at startup walks up from its working directory to find
# .coordination/local.env (gitignored) and overrides these
# placeholders with the real values it carries. Keeping the tracked
# templates at placeholders is what makes them safe to commit
# publicly; tests/test_deploy_overlay.py is the leak guard that
# enforces this. coordination/mcp_server.py:_load_local_env contains
# the matching override logic.
PLACEHOLDER_API_URL = "http://127.0.0.1:8080"
PLACEHOLDER_AUTH_TOKEN = "set-me"
PLACEHOLDER_REPO_ID = "example-org/example-repo"


def _update_mcp_json(path: Path) -> bool:
    """Write or refresh the tracked .mcp.json template (also used for
    .cursor/mcp.json). Always emits the documented placeholder values;
    the real service URL, bearer token, and repo identifier flow
    exclusively through .coordination/local.env, which the MCP
    wrapper resolves at startup. See PLACEHOLDER_* constants above
    for the reasoning.

    Returns True on success. Mirrors cli_mcp._write_json_config's refusal
    contract: an existing file that is not valid JSON, not a JSON object,
    or has a non-object ``mcpServers`` is left untouched (False) with a
    clear message -- silently replacing it would destroy the user's other
    MCP servers over a trailing-comma typo."""
    path.parent.mkdir(parents=True, exist_ok=True)
    data: dict = {}
    if path.exists():
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError as exc:
            print(
                f"Warning: cannot read {path}: {exc}; leaving it untouched.",
                file=sys.stderr,
            )
            return False
        if raw.strip():
            try:
                loaded = json.loads(raw)
            except json.JSONDecodeError as exc:
                print(
                    f"Warning: {path} is not valid JSON ({exc}); refusing to "
                    "overwrite it. Fix or remove the file and re-run.",
                    file=sys.stderr,
                )
                return False
            if not isinstance(loaded, dict):
                print(
                    f"Warning: {path} does not contain a JSON object; "
                    "refusing to overwrite it. Fix or remove the file and "
                    "re-run.",
                    file=sys.stderr,
                )
                return False
            data = loaded
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        print(
            f'Warning: {path} has a non-object "mcpServers"; refusing to '
            "overwrite it. Fix or remove the file and re-run.",
            file=sys.stderr,
        )
        return False
    servers["coord"] = {
        "command": "coord-mcp",
        "args": [],
        "env": {
            "COORD_API_URL": PLACEHOLDER_API_URL,
            "COORD_AUTH_TOKEN": PLACEHOLDER_AUTH_TOKEN,
            "COORD_REPO_ID": PLACEHOLDER_REPO_ID,
        },
    }
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return True


def _update_codex_config(path: Path) -> None:
    """Write Codex's MCP server entry for coord with the documented
    placeholder env block. Codex spawns ``coord-mcp`` without sourcing
    ``.coordination/local.env`` directly, so the wrapper itself loads
    that file on startup and overrides the placeholders below with
    the real values. The tracked file must NEVER carry real config;
    the leak guard in tests/test_deploy_overlay.py is the regression
    check (mirrors the .mcp.json contract)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "[mcp_servers.coord]\n",
        'command = "coord-mcp"\n',
        "args = []\n",
        "enabled = true\n",
        "required = false\n",
        "tool_timeout_sec = 30\n",
        "\n[mcp_servers.coord.env]\n",
        f'COORD_API_URL = "{PLACEHOLDER_API_URL}"\n',
        f'COORD_AUTH_TOKEN = "{PLACEHOLDER_AUTH_TOKEN}"\n',
        f'COORD_REPO_ID = "{PLACEHOLDER_REPO_ID}"\n',
    ]
    path.write_text("".join(parts), encoding="utf-8")


def _git_hook_path(repo_root: Path) -> Path | None:
    """Resolve the path of the ``pre-push`` git hook for ``repo_root``.

    A normal main worktree keeps hooks under ``<repo_root>/.git/hooks`` and
    is returned directly (unchanged legacy behaviour). A LINKED git worktree
    has ``<repo_root>/.git`` as a file (a gitdir pointer), not a directory,
    so the legacy ``<repo_root>/.git/hooks/pre-push`` path crashed
    ``coord init`` / ``coord upgrade`` with ``NotADirectoryError``; there we
    ask git for the real (shared) hooks path instead. Returns ``None`` when
    ``repo_root`` is not inside a git work tree, so the caller can skip the
    shim instead of raising.
    """
    dot_git = repo_root / ".git"
    if dot_git.is_dir():
        return dot_git / "hooks" / "pre-push"
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks/pre-push"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            check=False,
        )
    except (FileNotFoundError, OSError):
        return None
    if result.returncode != 0:
        return None
    raw = result.stdout.strip()
    if not raw:
        return None
    path = Path(raw)
    if not path.is_absolute():
        path = (repo_root / path).resolve()
    return path


def _install_hook(repo_root: Path, force: bool) -> None:
    managed_hook = repo_root / ".coordination" / "hooks" / "pre-push"
    write_executable(managed_hook, PRE_PUSH_SCRIPT)
    git_hook = _git_hook_path(repo_root)
    if git_hook is None:
        print(
            "Note: could not locate the git hooks directory (is this inside a "
            "git work tree?); skipping the .git/hooks/pre-push shim. The "
            "managed helper at .coordination/hooks/pre-push was still written.",
            file=sys.stderr,
        )
        return
    git_hook.parent.mkdir(parents=True, exist_ok=True)
    shim = (
        "#!/usr/bin/env bash\n"
        "# Resolve coord's managed pre-push helper relative to the MAIN\n"
        "# worktree root, not whichever worktree we were invoked from. In a\n"
        "# linked git worktree `git rev-parse --show-toplevel` points at the\n"
        "# linked root (which has no .coordination/), so we derive the main\n"
        "# root from the common git dir's parent instead. Fail open (exit 0)\n"
        "# if we cannot resolve it or the helper is missing -- coord must\n"
        "# never hard-block a push just because it cannot find its own helper.\n"
        'common="$(git rev-parse --git-common-dir 2>/dev/null)"\n'
        '[ -n "$common" ] || exit 0\n'
        'repo_root="$(cd "$common/.." 2>/dev/null && pwd)" || exit 0\n'
        '[ -n "$repo_root" ] || exit 0\n'
        'helper="$repo_root/.coordination/hooks/pre-push"\n'
        '[ -x "$helper" ] && exec "$helper" "$@"\n'
        "exit 0\n"
    )

    # CRITICAL: never follow a symlink with write_text. The target is
    # often a tracked repo file (e.g. scripts/git-hooks/pre-push) with
    # real CI / lint / deploy logic; writing the shim through the
    # symlink silently destroys that content. We refuse and print
    # guidance so the user can chain coord into their existing hook
    # explicitly. The same logic applies under --force: --force is for
    # overwriting *coord's* own files, not the user's tracked hooks.
    if git_hook.is_symlink():
        target = os.readlink(git_hook)
        print(
            f"Warning: .git/hooks/pre-push is a symlink to {target!r}.\n"
            f"  coord did not modify it (writing would clobber the symlink target,\n"
            f"  which is often a tracked repo file with real CI logic).\n"
            f"  To run coord's conflict check alongside your existing hook, add\n"
            f"  this near the end of {target}:\n"
            f"\n"
            f"    COORD_HOOK=\"$(cd \"$(git rev-parse --git-common-dir)/..\" && pwd)/.coordination/hooks/pre-push\"\n"
            f"    [ -x \"$COORD_HOOK\" ] && \"$COORD_HOOK\" \"$@\"\n",
            file=sys.stderr,
        )
        return

    if git_hook.exists() and "coordination/hooks/pre-push" not in git_hook.read_text(encoding="utf-8"):
        if not force:
            print(
                "Note: .git/hooks/pre-push exists and is not the coord shim;\n"
                "  leaving it untouched. Re-run with --force to overwrite, or\n"
                "  chain coord's check by adding this line near the end of\n"
                "  your existing hook:\n"
                "\n"
                "    COORD_HOOK=\"$(cd \"$(git rev-parse --git-common-dir)/..\" && pwd)/.coordination/hooks/pre-push\"\n"
                "    [ -x \"$COORD_HOOK\" ] && \"$COORD_HOOK\" \"$@\"\n",
                file=sys.stderr,
            )
            return
        # Force-overwrite: keep a backup so the user can recover if this
        # was unintended.
        backup = git_hook.with_suffix(git_hook.suffix + ".bak")
        try:
            backup.write_text(
                git_hook.read_text(encoding="utf-8"), encoding="utf-8"
            )
            print(
                f"Note: previous .git/hooks/pre-push backed up to {backup.name}.",
                file=sys.stderr,
            )
        except OSError:
            pass

    write_executable(git_hook, shim)


def _probe_service(service_url: str) -> bool:
    try:
        response = httpx.get(f"{service_url}/readyz", timeout=1.0)
    except httpx.HTTPError:
        return False
    return response.status_code == 200


def _resolve_root(explicit: str | None) -> Path | None:
    """Return the base path where .coordination/ should live.

    When --root is omitted, fall back to the enclosing git repo root.
    When --root is supplied, resolve it (relative paths are resolved against
    cwd), verify the directory exists, and verify it is inside a git work
    tree (walk up until a .git is found). Returns None on failure so the
    caller can emit a clear error and exit non-zero.
    """
    if explicit is None:
        return find_repo_root()
    candidate = Path(explicit)
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve()
    if not candidate.exists() or not candidate.is_dir():
        print(
            f"--root path does not exist or is not a directory: {candidate}",
            file=sys.stderr,
        )
        return None
    # Walk up from the candidate to verify it is inside a git work tree.
    # The work tree root does not have to equal candidate (monorepo case).
    enclosing = find_repo_root(candidate)
    if enclosing is None:
        print(
            f"--root path is not inside a git work tree: {candidate}",
            file=sys.stderr,
        )
        return None
    return candidate


def run_init(args) -> int:
    repo_root = _resolve_root(getattr(args, "root", None))
    if repo_root is None:
        if getattr(args, "root", None) is None:
            print("Not inside a git repository.")
        # _resolve_root already printed a specific message for --root failures.
        return 1

    tool = _determine_tool(args)
    mode = _determine_mode(args)
    service_url = _service_url(mode, args.service_url)

    if mode == "local" and not _probe_service(service_url):
        print(
            f"Warning: coordination service not reachable at {service_url}. "
            "Run 'coord start --background' first so agents can connect.",
            file=sys.stderr,
        )

    written: list[str] = []

    repo_id = _detect_repo_id(repo_root)
    _write_repo_config(repo_root, tool, mode, service_url, repo_id=repo_id)
    written.append(".coordination/config.toml")

    if _write_local_env(
        repo_root, mode, service_url, repo_id=repo_id, force=args.force
    ):
        written.append(".coordination/local.env (existing token preserved)")
    else:
        written.append(".coordination/local.env")

    # NOTE: we deliberately do NOT pass service_url / token / repo_id to the
    # tracked-template writers below. Those files (.mcp.json,
    # .codex/config.toml, .cursor/mcp.json) live in version control and must
    # never carry the real bearer token or hostname; the MCP wrapper resolves
    # both from .coordination/local.env (gitignored) at startup. See
    # PLACEHOLDER_* constants above and tests/test_deploy_overlay.py.

    if not args.no_owners:
        owners_path = repo_root / ".coordination" / "owners.yaml"
        owners_path.parent.mkdir(parents=True, exist_ok=True)
        if not owners_path.exists() or args.force:
            owners_path.write_text(_starter_owners(repo_root), encoding="utf-8")
            written.append(".coordination/owners.yaml")

    # Coord-generated machine config files (JSON) that a Prettier-using
    # repo would otherwise format-check and fail on. Collected per tool
    # and exempted via .prettierignore once below.
    prettier_targets: list[str] = []
    wiring_failed = False
    if tool == "claude":
        if _update_mcp_json(repo_root / ".mcp.json"):
            written.append(".mcp.json")
            prettier_targets.append(".mcp.json")
        else:
            wiring_failed = True
        ensure_managed_block(repo_root / "CLAUDE.md", CLAUDE_SNIPPET)
        written.append("CLAUDE.md (managed block)")
    elif tool == "codex":
        _update_codex_config(repo_root / ".codex" / "config.toml")
        ensure_managed_block(repo_root / "AGENTS.md", AGENTS_SNIPPET)
        written.extend([".codex/config.toml", "AGENTS.md (managed block)"])
    else:
        if _update_mcp_json(repo_root / ".cursor" / "mcp.json"):
            written.append(".cursor/mcp.json")
            prettier_targets.append(".cursor/mcp.json")
        else:
            wiring_failed = True
        ensure_managed_block(repo_root / ".cursor" / "rules" / "coordination.mdc", CURSOR_RULE)
        written.append(".cursor/rules/coordination.mdc")

    if ensure_prettierignore_entries(repo_root, prettier_targets):
        written.append(".prettierignore (managed block)")

    if not args.no_hook:
        _install_hook(repo_root, args.force)
        written.append(".coordination/hooks/pre-push")
        written.append(".git/hooks/pre-push (shim)")

    # Ignore the entire .coordination/ directory (per-developer state)
    # AND coord's generated machine configs. Two hard-won lessons:
    # (1) a narrow .coordination/local.env rule left config.toml /
    # owners.yaml / hooks/ exposed to `git stash -u` pop conflicts that
    # silently dropped them; widening to the whole dir makes that
    # impossible. (2) tracking .mcp.json (and the cursor/codex configs)
    # let a careless `git add -A` sweep coord wiring into contributor
    # PRs; gitignoring them keeps the configs local. Real per-repo
    # config lives only in .coordination/local.env.
    ensure_gitignore_entries(repo_root, ["/.coordination/", *_MACHINE_CONFIGS])
    written.append(".gitignore (managed block)")

    # Untrack any machine config an older coord version committed, so
    # the new gitignore actually takes effect (gitignore does not
    # untrack already-tracked files).
    for rel in _untrack_machine_configs(repo_root):
        written.append(f"{rel} (untracked from git)")

    print(f"Initialized coordination for {repo_root}")
    print(f"Tool: {tool}    Mode: {mode}    Service: {service_url}")
    print(f"Repo id: {repo_id}")
    print("")
    print("Wrote or updated:")
    for path in written:
        print(f"  {path}")
    print("")
    print("Next step: coord doctor")
    _warn_tracked_wiring_commit_risk(repo_root, written)
    if wiring_failed:
        print(
            "One or more MCP configs could not be written (see warnings "
            "above). Fix or remove the file(s) and re-run 'coord init'.",
            file=sys.stderr,
        )
        return 1
    return 0

