from __future__ import annotations

from datetime import timedelta
import json
import os
from pathlib import Path
import re
import secrets
import shlex
import stat
import sys

MANAGED_BEGIN = "<!-- coord:begin -->"
MANAGED_END = "<!-- coord:end -->"
# Markdown-comment markers above are invisible in rendered Markdown,
# which is what managed CLAUDE.md / AGENTS.md / cursor blocks want. But
# .gitignore (and other shell-comment files) treats `<!--` as a literal
# pattern character, so we use real shell-comment markers there. Both
# styles are accepted on read so an upgrade against an older repo
# migrates the file to the right style without losing the entry.
MANAGED_HASH_BEGIN = "# coord:begin"
MANAGED_HASH_END = "# coord:end"

# Embedded inside every managed block as a self-documenting warning.
# The MANAGED_BEGIN markers themselves are too cryptic for an agent
# that has never read the coord source -- including this line as
# block content makes the contract obvious in any rendering.
_MANAGED_WARNING = (
    "AUTO-GENERATED by 'coord upgrade'. "
    "Do not hand-edit; next upgrade will overwrite."
)

# Fixed command-line fragment we expect for a coord background service.
# Used to verify via `ps` that a recorded PID actually belongs to us (and not
# to some unrelated process that reused the PID after ours exited).
COORD_SERVE_MARKER = "coordination.cli _serve"

# Operator-facing durations (token expiry, rotation grace) are a bare
# integer plus a single unit letter. Deliberately strict: no floats, no
# compound forms like "1h30m", no signs. An operator who needs 90
# minutes writes 90m -- one obvious spelling per duration keeps flag
# values grep-able and copy-paste safe.
_DURATION_RE = re.compile(r"^(\d+)([mhdw])$")

_DURATION_UNITS = {
    "m": timedelta(minutes=1),
    "h": timedelta(hours=1),
    "d": timedelta(days=1),
    "w": timedelta(weeks=1),
}


def parse_duration(value: str, *, allow_zero: bool = False) -> timedelta:
    """Parse an operator duration like ``30d``, ``12h``, ``45m`` or
    ``2w`` into a timedelta. Only ``<digits><unit>`` with a unit of
    m/h/d/w is accepted; anything else (missing unit, negative, float,
    empty, unknown unit) raises ValueError with a message suitable for
    printing straight to stderr. Zero durations also raise unless
    ``allow_zero`` is set -- ``--grace 0h`` is a meaningful "cut over
    immediately", but ``--expires-in 0h`` would mint a dead token."""
    match = _DURATION_RE.fullmatch(value or "")
    if match is None:
        raise ValueError(
            f"Invalid duration {value!r}: expected a whole number plus "
            "a unit of m/h/d/w (e.g. 30d, 12h, 45m, 2w)."
        )
    count = int(match.group(1))
    if count == 0 and not allow_zero:
        raise ValueError(
            f"Invalid duration {value!r}: must be greater than zero."
        )
    return count * _DURATION_UNITS[match.group(2)]


def format_repo_scoped_token_create_command(
    engineer: str, repo_id: str | None
) -> str:
    """Return a copy-pasteable scoped-token creation command.

    Used in human hints where the safe default should be repo-scoped. A
    placeholder engineer stays visually placeholder-like; real engineer ids
    are shell-quoted when needed, and leading-dash ids use argparse's ``--``
    separator so the command remains valid.
    """
    repo = repo_id or "<owner/name>"
    repo_arg = repo if repo.startswith("<") and repo.endswith(">") else shlex.quote(repo)
    if engineer == "<engineer>":
        who = '"<engineer>"'
        starts_dash = False
    else:
        starts_dash = engineer.startswith("-")
        who = shlex.quote(engineer)
    if starts_dash:
        return f"coord tokens create --repo {repo_arg} -- {who}"
    return f"coord tokens create {who} --repo {repo_arg}"


def coord_home() -> Path:
    return Path(os.environ.get("COORD_HOME", "~/.coord")).expanduser()


def state_paths() -> dict[str, Path]:
    home = coord_home()
    return {
        "home": home,
        "data_dir": home / "data",
        "database_path": home / "data" / "coordination.db",
        "token_file": home / "token",
    }


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def ensure_token_file(path: Path) -> str:
    ensure_parent(path)
    if path.exists():
        token = path.read_text(encoding="utf-8").strip()
        if token:
            return token
    token = secrets.token_urlsafe(24)
    path.write_text(f"{token}\n", encoding="utf-8")
    try:
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass
    return token


def find_repo_root(start: Path | None = None) -> Path | None:
    current = (start or Path.cwd()).resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return candidate
    return None


def _replace_either_marker_style(text: str, new_block: str) -> str | None:
    """Try to replace whichever marker style is present in ``text`` with
    ``new_block``. Returns the rewritten text on success, ``None`` if no
    managed block was found. The two-pass design lets a repo created
    with a previous coord version (or hand-edited by an agent that
    swapped marker styles) be migrated to the right style without
    losing content."""
    for begin, end in (
        (MANAGED_BEGIN, MANAGED_END),
        (MANAGED_HASH_BEGIN, MANAGED_HASH_END),
    ):
        pattern = re.compile(
            rf"{re.escape(begin)}.*?{re.escape(end)}\n?",
            re.DOTALL,
        )
        if pattern.search(text):
            return pattern.sub(new_block, text, count=1)
    return None


def ensure_managed_block(path: Path, content: str) -> None:
    """Write a managed block to a Markdown file. The block is wrapped
    in HTML-comment markers (invisible in rendered Markdown) and its
    first line is an AUTO-GENERATED warning so a hand-editor sees the
    contract before the body."""
    ensure_parent(path)
    block = (
        f"{MANAGED_BEGIN}\n"
        f"<!-- {_MANAGED_WARNING} -->\n"
        f"{content.strip()}\n"
        f"{MANAGED_END}\n"
    )
    if not path.exists():
        path.write_text(block, encoding="utf-8")
        return
    existing = path.read_text(encoding="utf-8")
    replaced = _replace_either_marker_style(existing, block)
    if replaced is not None:
        path.write_text(replaced, encoding="utf-8")
        return
    suffix = "\n" if existing and not existing.endswith("\n") else ""
    path.write_text(f"{existing}{suffix}\n{block}", encoding="utf-8")


def has_managed_block(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    return MANAGED_BEGIN in text or MANAGED_HASH_BEGIN in text


def _ensure_managed_hash_entry(path: Path, entry: str) -> None:
    """Write ``entry`` into ``path`` inside a hash-comment managed block.

    Shared by the .gitignore and .prettierignore writers -- both use
    gitignore-style syntax where ``# coord:begin`` is a valid comment.
    Hash-style markers are used (not the HTML-comment style of managed
    Markdown blocks) because ``<!--`` parses as a literal path pattern
    here. The replacement pass detects either marker style so a repo
    created by an older coord version migrates cleanly without losing
    the entry. ``entry`` may be multi-line (one path per line) to manage
    several paths in a single block.
    """
    block = (
        f"{MANAGED_HASH_BEGIN}\n"
        f"# {_MANAGED_WARNING}\n"
        f"{entry}\n"
        f"{MANAGED_HASH_END}\n"
    )
    if not path.exists():
        ensure_parent(path)
        path.write_text(block, encoding="utf-8")
        return
    existing = path.read_text(encoding="utf-8")
    replaced = _replace_either_marker_style(existing, block)
    if replaced is not None:
        path.write_text(replaced, encoding="utf-8")
        return
    if entry in existing.splitlines():
        # Entry already present outside any managed block; do not double-add.
        return
    suffix = "\n" if existing and not existing.endswith("\n") else ""
    path.write_text(f"{existing}{suffix}\n{block}", encoding="utf-8")


def ensure_gitignore_entry(repo_root: Path, entry: str) -> None:
    """Write a managed gitignore entry using shell-comment markers.

    Hash-style markers are valid gitignore comment syntax; the older
    HTML-style markers are not (they parse as never-matching path
    patterns, which is silently noisy and prompts agents to "fix"
    them). The replacement pass detects either style, so a repo
    upgrading from an older coord version migrates cleanly without
    losing the entry.
    """
    _ensure_managed_hash_entry(repo_root / ".gitignore", entry)


def ensure_gitignore_entries(repo_root: Path, entries: list[str]) -> None:
    """Write several managed .gitignore entries in a single block (one
    path per line). Used by init/upgrade to ignore the ``.coordination/``
    state directory AND coord's generated machine configs (``.mcp.json``,
    ``.cursor/mcp.json``, ``.codex/config.toml``) so the configs are
    never tracked into a contributor PR. No-op on an empty list."""
    if not entries:
        return
    _ensure_managed_hash_entry(repo_root / ".gitignore", "\n".join(entries))


# Standalone Prettier config filenames. Presence of any one (or a
# .prettierignore, or a prettier key / dependency in package.json) means
# the repo runs ``prettier --check``, so coord's generated machine config
# would gate the repo's format CI unless we exempt it.
_PRETTIER_CONFIG_FILES = (
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.json5",
    ".prettierrc.yaml",
    ".prettierrc.yml",
    ".prettierrc.toml",
    ".prettierrc.js",
    ".prettierrc.cjs",
    ".prettierrc.mjs",
    "prettier.config.js",
    "prettier.config.cjs",
    "prettier.config.mjs",
)


def repo_uses_prettier(repo_root: Path) -> bool:
    """True when the repo appears to run Prettier. Detects a standalone
    config file, an existing .prettierignore, or a ``prettier`` key /
    dependency in package.json. Coord uses this to decide whether to add
    its generated config to .prettierignore -- we never drop a stray
    .prettierignore into a repo that does not use Prettier."""
    if (repo_root / ".prettierignore").exists():
        return True
    for name in _PRETTIER_CONFIG_FILES:
        if (repo_root / name).exists():
            return True
    pkg = repo_root / "package.json"
    if pkg.exists():
        try:
            data = json.loads(pkg.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            return False
        if isinstance(data, dict):
            if "prettier" in data:
                return True
            for dep_key in ("devDependencies", "dependencies"):
                deps = data.get(dep_key)
                if isinstance(deps, dict) and "prettier" in deps:
                    return True
    return False


def ensure_prettierignore_entries(repo_root: Path, entries: list[str]) -> bool:
    """If the repo uses Prettier, list ``entries`` (coord-generated
    machine config paths such as ``.mcp.json``) in ``.prettierignore``
    under a single managed block, and return True. Generated config is
    the analogue of package-lock.json: it must never gate a repo's
    format check, and re-running ``coord upgrade`` would otherwise
    re-break a previously green CI. Returns False (no-op) when there are
    no entries or the repo does not use Prettier, so onboarding never
    drops a stray .prettierignore into an unrelated repo."""
    if not entries or not repo_uses_prettier(repo_root):
        return False
    _ensure_managed_hash_entry(repo_root / ".prettierignore", "\n".join(entries))
    return True


def write_executable(path: Path, content: str) -> None:
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    try:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def local_coord_mcp_path() -> Path:
    return Path(sys.executable).parent / "coord-mcp"

