from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import httpx

from coordination.assets import AGENTS_SNIPPET, CLAUDE_SNIPPET, CURSOR_RULE, PRE_PUSH_SCRIPT
from coordination.cli_shared import (
    ensure_gitignore_entry,
    ensure_managed_block,
    ensure_token_file,
    find_repo_root,
    state_paths,
    write_executable,
)
from coordination.repo_config import RepoConfig


def _prompt_choice(prompt: str, choices: list[str], default: str) -> str:
    options = "/".join(choices)
    raw = input(f"{prompt} [{options}] ({default}): ").strip().lower()
    return raw if raw in choices else default


def _determine_tool(args) -> str:
    if args.tool:
        return args.tool
    if args.yes:
        return "claude"
    return _prompt_choice("Primary coding tool", ["claude", "codex", "cursor"], "claude")


def _determine_mode(args) -> str:
    if args.mode:
        return args.mode
    if args.yes:
        return "local"
    return _prompt_choice("Connection mode", ["local", "remote"], "local")


def _service_url(mode: str, explicit: str | None) -> str:
    if explicit:
        return explicit.rstrip("/")
    if mode == "local":
        return "http://127.0.0.1:8080"
    return "https://coord.example.com"


def _starter_owners(repo_root: Path) -> str:
    lines = [
        "# Starter ownership map generated by coord init",
        "# Tighten these boundaries as your team learns where conflicts happen.",
        "",
        "areas:",
    ]
    dirs = sorted(
        p.name
        for p in repo_root.iterdir()
        if p.is_dir() and not p.name.startswith(".") and p.name not in {"node_modules", "dist", "build"}
    )
    if not dirs:
        dirs = ["src"]
    for name in dirs[:8]:
        lines.extend(
            [
                f"  {name}:",
                "    paths:",
                f'      - "{name}/**"',
                "    owners: [team]",
                "",
            ]
        )
    lines.extend(
        [
            "  shared-root:",
            "    paths:",
            '      - "package.json"',
            '      - "README.md"',
            "    severity: hard",
            "    owners: [all]",
            "",
        ]
    )
    return "\n".join(lines)


def _detect_repo_id(repo_root: Path) -> str:
    """Best-effort repo identifier for a coord-managed repo.

    Order of preference:
    1. ``owner/repo`` slug parsed from ``git remote get-url origin``.
       Handles both HTTPS (``https://github.com/owner/repo.git``) and
       SSH (``git@github.com:owner/repo.git``) forms.
    2. The directory basename, when no origin remote is configured or
       the directory is not a git work tree.

    Never raises: a reliable repo id is more useful than a precise one,
    and the user can always override the value with an explicit
    ``repo_id`` in ``.coordination/config.toml``.
    """
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_root,
            check=False,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError):
        return repo_root.name

    if result.returncode != 0:
        return repo_root.name

    url = result.stdout.strip()
    # SSH form: git@host:owner/repo(.git)
    m = re.match(r"^[^@]+@[^:]+:([^/]+/[^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1)
    # HTTPS / git protocol form: scheme://host/path/owner/repo(.git)
    m = re.match(r"^[a-zA-Z]+://[^/]+/(?:[^/]+/)*([^/]+/[^/]+?)(?:\.git)?$", url)
    if m:
        return m.group(1)
    return repo_root.name


def _write_repo_config(
    repo_root: Path,
    tool: str,
    mode: str,
    service_url: str,
    repo_id: str | None = None,
) -> None:
    config = RepoConfig(
        version=1,
        tool=tool,
        mode=mode,
        service_url=service_url,
        ownership_file=".coordination/owners.yaml",
        repo_id=repo_id or _detect_repo_id(repo_root),
    )
    path = repo_root / ".coordination" / "config.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config.to_toml(), encoding="utf-8")


def _write_local_env(
    repo_root: Path, mode: str, service_url: str, repo_id: str | None = None
) -> None:
    if mode == "local":
        token = ensure_token_file(state_paths()["token_file"])
    else:
        token = os.environ.get("COORD_AUTH_TOKEN", "set-me")
    path = repo_root / ".coordination" / "local.env"
    path.parent.mkdir(parents=True, exist_ok=True)
    # COORD_API_URL powers coord-mcp and user shells; COORD_SERVICE_URL is
    # what the pre-push hook reads. Emit both so whichever tool sources
    # this file picks up the right endpoint -- this is what stops a remote
    # deployment from silently falling back to http://127.0.0.1:8080.
    body = (
        f"COORD_API_URL={service_url}\n"
        f"COORD_SERVICE_URL={service_url}\n"
        f"COORD_AUTH_TOKEN={token}\n"
    )
    rid = repo_id or _detect_repo_id(repo_root)
    if rid:
        body += f"COORD_REPO_ID={rid}\n"
    path.write_text(body, encoding="utf-8")


def _update_mcp_json(
    path: Path, service_url: str, token: str, repo_id: str | None = None
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = {}
    else:
        data = {}
    servers = data.setdefault("mcpServers", {})
    env: dict[str, str] = {
        "COORD_API_URL": service_url,
        "COORD_AUTH_TOKEN": token,
    }
    if repo_id:
        env["COORD_REPO_ID"] = repo_id
    servers["coord"] = {
        "command": "coord-mcp",
        "args": [],
        "env": env,
    }
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _update_codex_config(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "[mcp_servers.coord]\n"
        'command = "coord-mcp"\n'
        "args = []\n"
        "enabled = true\n"
        "required = false\n"
        "tool_timeout_sec = 30\n"
        "\n"
        "# Set in your shell or .coordination/local.env:\n"
        '#   export COORD_API_URL="https://YOUR_COORD_SERVICE.example"\n'
        '#   export COORD_AUTH_TOKEN="..."\n'
    )
    path.write_text(content, encoding="utf-8")


def _install_hook(repo_root: Path, force: bool) -> None:
    managed_hook = repo_root / ".coordination" / "hooks" / "pre-push"
    write_executable(managed_hook, PRE_PUSH_SCRIPT)
    git_hook = repo_root / ".git" / "hooks" / "pre-push"
    shim = (
        "#!/usr/bin/env bash\n"
        'exec "$(git rev-parse --show-toplevel)/.coordination/hooks/pre-push" "$@"\n'
    )
    if git_hook.exists() and "coordination/hooks/pre-push" not in git_hook.read_text(encoding="utf-8"):
        if not force:
            return
    write_executable(git_hook, shim)


def _probe_service(service_url: str) -> bool:
    try:
        response = httpx.get(f"{service_url}/readyz", timeout=1.0)
    except httpx.HTTPError:
        return False
    return response.status_code == 200


def _resolve_root(explicit: str | None) -> Path | None:
    """Return the base path where .coordination/ should live.

    When --root is omitted, fall back to the enclosing git repo root.
    When --root is supplied, resolve it (relative paths are resolved against
    cwd), verify the directory exists, and verify it is inside a git work
    tree (walk up until a .git is found). Returns None on failure so the
    caller can emit a clear error and exit non-zero.
    """
    if explicit is None:
        return find_repo_root()
    candidate = Path(explicit)
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve()
    if not candidate.exists() or not candidate.is_dir():
        print(
            f"--root path does not exist or is not a directory: {candidate}",
            file=sys.stderr,
        )
        return None
    # Walk up from the candidate to verify it is inside a git work tree.
    # The work tree root does not have to equal candidate (monorepo case).
    enclosing = find_repo_root(candidate)
    if enclosing is None:
        print(
            f"--root path is not inside a git work tree: {candidate}",
            file=sys.stderr,
        )
        return None
    return candidate


def run_init(args) -> int:
    repo_root = _resolve_root(getattr(args, "root", None))
    if repo_root is None:
        if getattr(args, "root", None) is None:
            print("Not inside a git repository.")
        # _resolve_root already printed a specific message for --root failures.
        return 1

    tool = _determine_tool(args)
    mode = _determine_mode(args)
    service_url = _service_url(mode, args.service_url)

    if mode == "local" and not _probe_service(service_url):
        print(
            f"Warning: coordination service not reachable at {service_url}. "
            "Run 'coord start --background' first so agents can connect.",
            file=sys.stderr,
        )

    written: list[str] = []

    repo_id = _detect_repo_id(repo_root)
    _write_repo_config(repo_root, tool, mode, service_url, repo_id=repo_id)
    written.append(".coordination/config.toml")

    _write_local_env(repo_root, mode, service_url, repo_id=repo_id)
    written.append(".coordination/local.env")

    # Pick the COORD_AUTH_TOKEN line specifically rather than the first line,
    # which after this change is COORD_API_URL.
    token = ""
    for line in (repo_root / ".coordination" / "local.env").read_text(encoding="utf-8").splitlines():
        if line.startswith("COORD_AUTH_TOKEN="):
            token = line.split("=", 1)[1].strip()
            break

    if not args.no_owners:
        owners_path = repo_root / ".coordination" / "owners.yaml"
        owners_path.parent.mkdir(parents=True, exist_ok=True)
        if not owners_path.exists() or args.force:
            owners_path.write_text(_starter_owners(repo_root), encoding="utf-8")
            written.append(".coordination/owners.yaml")

    if tool == "claude":
        _update_mcp_json(
            repo_root / ".mcp.json", service_url, token, repo_id=repo_id
        )
        ensure_managed_block(repo_root / "CLAUDE.md", CLAUDE_SNIPPET)
        written.extend([".mcp.json", "CLAUDE.md (managed block)"])
    elif tool == "codex":
        _update_codex_config(repo_root / ".codex" / "config.toml")
        ensure_managed_block(repo_root / "AGENTS.md", AGENTS_SNIPPET)
        written.extend([".codex/config.toml", "AGENTS.md (managed block)"])
    else:
        _update_mcp_json(
            repo_root / ".cursor" / "mcp.json", service_url, token, repo_id=repo_id
        )
        ensure_managed_block(repo_root / ".cursor" / "rules" / "coordination.mdc", CURSOR_RULE)
        written.extend([".cursor/mcp.json", ".cursor/rules/coordination.mdc"])

    if not args.no_hook:
        _install_hook(repo_root, args.force)
        written.append(".coordination/hooks/pre-push")
        written.append(".git/hooks/pre-push (shim)")

    ensure_gitignore_entry(repo_root, ".coordination/local.env")
    written.append(".gitignore (managed block)")

    print(f"Initialized coordination for {repo_root}")
    print(f"Tool: {tool}    Mode: {mode}    Service: {service_url}")
    print(f"Repo id: {repo_id}")
    print("")
    print("Wrote or updated:")
    for path in written:
        print(f"  {path}")
    print("")
    print("Next step: coord doctor")
    return 0

